### ISSUE TITLE
Crashes on Kubuntu 18.10

### ISSUE THREAD

**Issue by Lorchi74** [LuminanceHDR/LuminanceHDR#165]
Hello, I encountered reproducible crashes. Here is the information. Best regards!

- Luminance HDR 2.5.1, installed using package manager
- Kubuntu 18.10
- Qt 5.11.1
- Kde Plasma 5.13.5
- Kde Frameworks 5.50.0

gdb:
`Reading symbols from luminance-hdr...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/luminance-hdr 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe9840700 (LWP 3232)]
[New Thread 0x7fffe68c0700 (LWP 3233)]
[New Thread 0x7fffdfbcb700 (LWP 3234)]
[New Thread 0x7fffdd8d0700 (LWP 3235)]
libpng warning: iCCP: known incorrect sRGB profile
[New Thread 0x7fffd7fff700 (LWP 3239)]
[New Thread 0x7fffd77fe700 (LWP 3240)]
[New Thread 0x7fffd6ffd700 (LWP 3241)]
[New Thread 0x7fffd67fc700 (LWP 3242)]
void HdrWizard::resizeEvent(QResizeEvent*)
[New Thread 0x7fffd5a8c700 (LWP 3243)]
"HdrCreationManager::loadFiles(): Checking /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0148_dt.tif"
"HdrCreationManager::loadFiles(): Schedule loading for /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0148_dt.tif"
"HdrCreationManager::loadFiles(): Checking /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0149_dt.tif"
"HdrCreationManager::loadFiles(): Schedule loading for /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0149_dt.tif"
"HdrCreationManager::loadFiles(): Checking /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0150_dt.tif"
"HdrCreationManager::loadFiles(): Schedule loading for /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0150_dt.tif"
[New Thread 0x7fffd528b700 (LWP 3244)]
[New Thread 0x7fffd4a8a700 (LWP 3245)]
[New Thread 0x7fffb3fff700 (LWP 3246)]
"LoadFile: Loading data for /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0149_dt.tif"
"LoadFile: Loading data for /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0148_dt.tif"
"LoadFile: Loading data for /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0150_dt.tif"
TIFFReadDirectory: Warning, Unknown field with tag 18246 (0x4746) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 18249 (0x4749) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 36867 (0x9003) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 18246 (0x4746) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 18249 (0x4749) encountered.
TIFFReadDirectory: Warning, TiffReader: Unknown field with tag 36867 (0x9003) encountered.
iccProfileSize: 8940
TIFFReadDirectory: Warning, Unknown field with tag 18246 (0x4746) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 18249 (0x4749) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 36867 (0x9003) encountered.
void pfs::io::TiffReaderData::readRGB(pfs::Frame&, const pfs::io::TiffReaderParams&) [with InputDataType = short unsigned int]t
TiffReader: Available ICC Profile, building LCMS Transform
TiffReader: iccProfileSize: 8940
void pfs::io::TiffReaderData::readRGB(pfs::Frame&, const pfs::io::TiffReaderParams&) [with InputDataType = short unsigned int]t
TiffReader: Available ICC Profile, building LCMS Transform
TiffReader: iccProfileSize: 8940
void pfs::io::TiffReaderData::readRGB(pfs::Frame&, const pfs::io::TiffReaderParams&) [with InputDataType = short unsigned int]t
TiffReader: Available ICC Profile, building LCMS Transform
TiffReader: ICC Profile Available
TiffReader: ICC Profile Available
TiffReader: ICC Profile Available
[New Thread 0x7fffb37fe700 (LWP 3247)]
[New Thread 0x7fffb2ffd700 (LWP 3248)]
[New Thread 0x7fffb27fc700 (LWP 3249)]
[New Thread 0x7fffb1ffb700 (LWP 3250)]
[New Thread 0x7fffb17fa700 (LWP 3251)]
[New Thread 0x7fffb0ff9700 (LWP 3252)]
[New Thread 0x7fff647b5700 (LWP 3253)]
[New Thread 0x7fff63fb4700 (LWP 3254)]
[New Thread 0x7fff637b3700 (LWP 3255)]
CleanUpCmsTransform::cleanup()
"LoadFile: Average Luminance for /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0148_dt.tif is 0.00012251"
LoadFile:datamin = 0
LoadFile:datamax = 0.985977
CleanUpCmsTransform::cleanup()
CleanUpCmsTransform::cleanup()
"LoadFile: Average Luminance for /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0150_dt.tif is 0.00102679"
"LoadFile: Average Luminance for /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0149_dt.tif is 0.000331266"
CleanUpCmsProfile::cleanup()
CleanUpCmsProfile::cleanup()
CleanUpTiffFile::cleanup()
CleanUpCmsProfile::cleanup()
LoadFile:datamin = 0
LoadFile:datamax = 1
LoadFile:datamin = 0
LoadFile:datamax = 1
CleanUpCmsProfile::cleanup()
CleanUpCmsProfile::cleanup()
CleanUpTiffFile::cleanup()
CleanUpCmsProfile::cleanup()
CleanUpCmsProfile::cleanup()
CleanUpCmsProfile::cleanup()
CleanUpTiffFile::cleanup()
CleanUpCmsProfile::cleanup()
HdrCreationManager::loadFilesDone(): Data loaded ... move to internal structure!
"HdrCreationManager::loadFilesDone(): Insert data for /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0148_dt.tif"
"HdrCreationManager::loadFilesDone(): Insert data for /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0149_dt.tif"
"HdrCreationManager::loadFilesDone(): Insert data for /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0150_dt.tif"
"HdrCreationManager::refreshEVOffset(): offset = -11.5597"
HdrWizard::loadInputFilesDone()
HdrWizard::updateTableGrid(): Fill grid with values in the m_data structure
"HdrWizard::updateTableGrid(): Fill row 0: /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0148_dt.tif -12.9948 EV (-1.4351 EV)"
"HdrWizard::updateTableGrid(): Fill row 1: /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0149_dt.tif -11.5597 EV (0 EV)"
"HdrWizard::updateTableGrid(): Fill row 2: /home/henning/Pictures/1. Privat Chronologisch/2019/2019-04-27 Dächer und Himmel in Weilheim/proc/_MG_0150_dt.tif -9.92765 EV (1.63207 EV)"
"HdrWizard::inputHdrFileSelected(0)"
[Thread 0x7fffb3fff700 (LWP 3246) exited]
MergeDebevec = 7253.11 msec
Min Luminance:  1e-06
Max Luminance:  2.704
Mapping method:  3
[New Thread 0x7fffb3fff700 (LWP 3260)]
[New Thread 0x7fff9fab1700 (LWP 3261)]
[New Thread 0x7fff9f2b0700 (LWP 3262)]
luminance-hdr: /build/luminance-hdr-Tg2wfh/luminance-hdr-2.5.1+dfsg/src/Libpfs/colorspace/normalizer.h:43: float pfs::colorspace::Normalizer::operator()(float) const: Assertion `!boost::math::isnan(sample)' failed.
luminance-hdr: /build/luminance-hdr-Tg2wfh/luminance-hdr-2.5.1+dfsg/src/Libpfs/colorspace/normalizer.h:43: float pfs::colorspace::Normalizer::operator()(float) const: Assertion `!boost::math::isnan(sample)' failed.
luminance-hdr: /build/luminance-hdr-Tg2wfh/luminance-hdr-2.5.1+dfsg/src/Libpfs/colorspace/normalizer.h:43: float pfs::colorspace::Normalizer::operator()(float) const: Assertion `!boost::math::isnan(sample)' failed.
luminance-hdr: /build/luminance-hdr-Tg2wfh/luminance-hdr-2.5.1+dfsg/src/Libpfs/colorspace/normalizer.h:43: float pfs::colorspace::Normalizer::operator()(float) const: Assertion `!boost::math::isnan(sample)' failed.

Thread 1 "luminance-hdr" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff4dd0077 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff4db1535 in __GI_abort () at abort.c:79
#2  0x00007ffff4db140f in __assert_fail_base
    (fmt=0x7ffff4f3d858 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5555557ed138 "!boost::math::isnan(sample)", file=0x5555557ed0e0 "/build/luminance-hdr-Tg2wfh/luminance-hdr-2.5.1+dfsg/src/Libpfs/colorspace/normalizer.h", line=43, function=<optimized out>) at assert.c:92
#3  0x00007ffff4dc1142 in __GI___assert_fail
    (assertion=0x5555557ed138 "!boost::math::isnan(sample)", file=0x5555557ed0e0 "/build/luminance-hdr-Tg2wfh/luminance-hdr-2.5.1+dfsg/src/Libpfs/colorspace/normalizer.h", line=43, function=0x5555557f3e40 "float pfs::colorspace::Normalizer::operator()(float) const")
    at assert.c:101
#4  0x0000555555680e77 in QRgbRemapper::operator()(float, float, float, unsigned int&) const ()
#5  0x0000555555680f45 in  ()
#6  0x00007ffff4fa109f in GOMP_parallel () at /usr/lib/x86_64-linux-gnu/libgomp.so.1
#7  0x000055555568133f in fromLDRPFStoQImage(pfs::Frame*, float, float, RGBMappingType) ()
#8  0x00005555557230a9 in HdrViewer::HdrViewer(pfs::Frame*, QWidget*, bool) ()
#9  0x0000555555640b4e in MainWindow::load_success(pfs::Frame*, QString const&, QStringList const&, bool) ()
#10 0x00005555556420ab in MainWindow::createNewHdr(QStringList const&) ()
#11 0x000055555564213c in MainWindow::on_fileNewAction_triggered() ()
--Type <RET> for more, q to quit, c to continue without paging--c
#12 0x0000555555653163 in  ()
#13 0x00005555556535f3 in MainWindow::qt_metacall(QMetaObject::Call, int, void**) ()
#14 0x00007ffff55717ac in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff5f09ef2 in QAction::triggered(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff5f0c500 in QAction::activate(QAction::ActionEvent) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff5ff7d1d in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff5ff7f55 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff60e1caa in QToolButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff5f4e7d8 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff60e1d53 in QToolButton::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff5f104a1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff5f17d28 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff5548499 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff5f17029 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff5f69304 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff5f6be8e in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff5f104a1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff5f17ae0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007ffff5548499 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff594d53b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#32 0x00007ffff594f435 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#33 0x00007ffff5929b6b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#34 0x00007fffe87a1e5b in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#35 0x00007ffff554716b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007ffff554f2e2 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#37 0x000055555562a9e2 in main ()
`

**Comment by fcomida** [comment]
@Lorchi74 It happens in debug mode. Please build LHDR in release mode if you can.
